name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Common
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t qinbatista/v2rayserver \
            --build-arg V2RAY_CONFIG_URL="${{ vars.V2RAY_CONFIG_URL }}" \
            --build-arg V2RAY_CORE_URL="${{ vars.V2RAY_CORE_URL }}" \
            --push .
