name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: BuildEnv
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/v2rayserver . --build-arg V2RAY_DOWNLOADURL="${{ vars.V2RAY_DOWNLOADURL }}" --build-arg V2RAY_TARGETPLATFORM="${{ vars.V2RAY_TARGETPLATFORM }}" --build-arg V2RAY_TAG="${{ vars.V2RAY_TAG }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push qinbatista/v2rayserver
